formspree_form_id: formspree_form_id
name: Jekflix
title: Jekflix | A blog theme for Jekyll
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - sublimation
  - printing
  - tutorials
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
  - title: Category
    url: /categories
email: support@sublisnap.com
disqus_username: disqus_username
